#+TITLE: anchorage

Personal site.

* Table of Contents :toc:
- [[#the-sitch][The Sitch]]
- [[#disclaimer][Disclaimer]]
- [[#contributing][Contributing]]
- [[#code-of-conduct][Code of Conduct]]
- [[#license][License]]

* The Sitch
  I've also been discontent with my website and I must've changed it 10+ times now. This time I'm going to make it with
  modern technology and aim for a synergetic digital Hopefully this is the last time.

  Naming it =anchorage= to keep me anchored… hopefully :blush:.

* Disclaimer
  I might make this a reusable gatsby template in the future, but it's a burden right now while developing and it'd be a
  bit much to maintain it immediately.

  That said, feel free to contribute and help keep this clean and generalized enough to easily make it a template in the
  future (things like =xyz= should be a variable instead of declared inline).

* Contributing
  There are many ways in which you can participate in the project, for example:

  - See an open pull request? You can try reviewing it!
  - Find a pesky bug or perhaps a neat place to refactor? Report it in an issue or fix it with a PR!
  - Notice some weird or missing documentation? Fix or add it with a PR! (Lazy? Just report it in an issue :smile:)
  - Want to give a recommendation for a feature? Go ahead and open an issue.

  Feel free to open a pull request, check the [[file:CONTRIBUTING.org][contributing guide]] for more details.

* Code of Conduct
  WIP :shipit:

* License
  This project uses an MIT license, which can be viewed [[file:../LICENSE][here]].
